--[[****************************************************************************
  *                           _VirtualPlates                                   *
  * Totems/Totems-esES.lua - Localized TotemPlates table (es-ES).              *
  ****************************************************************************]]

if ( GetLocale() ~= "esES" ) then
	return;
end

local _VirtualPlates = select(2, ...)

local totemPath = "Interface\\AddOns\\!!!_VirtualPlates\\Textures\\Totems\\"
local npcPath = "Interface\\AddOns\\!!!_VirtualPlates\\Textures\\NPCs\\"

_VirtualPlates.TotemPlates = {
	-- Visible Totems
	["Tótem de limpieza"] = totemPath .. "Cleansing Totem.blp",
	["Tótem Elemental de Tierra"] = totemPath .. "Earth Elemental Totem.blp",
	["Tótem Nexo Terrestre"] = totemPath .. "Earthbind Totem.blp",
	["Tótem Elemental de Fuego"] = totemPath .. "Fire Elemental Totem.blp",
	["Tótem derribador"] = totemPath .. "Grounding Totem.blp",
	["Tótem Marea de maná"] = totemPath .. "Mana Tide Totem.blp",
	["Tótem de tremor"] = totemPath .. "Tremor Totem.blp",
	["Tótem Viento Furioso"] = totemPath .. "Windfury Totem.blp",
	["Tótem cólera de aire"] = totemPath .. "Wrath of Air Totem.blp",
	-- Visible NPCs
	["Confalón de batalla de la Alianza"] = npcPath .. "Alliance Battle Standard.blp", 
	["Confalón de batalla de la Horda"] = npcPath .. "Horde Battle Standard.blp",
	["Maligno de las Sombras"] = npcPath .. "Shadowfiend.blp",
	["Espíritu de lobo"] = npcPath .. "Spirit Wolf.blp",
	["Elemental de agua"] = npcPath .. "Water Elemental.blp",
	-- Hidden Totems
	["Tótem de resistencia al fuego"] = "",
	["Tótem de resistencia al fuego II"] = "",
	["Tótem de resistencia al fuego III"] = "",
	["Tótem de resistencia al fuego IV"] = "",
	["Tótem de resistencia al fuego V"] = "",
	["Tótem de resistencia al fuego VI"] = "",
	["Tótem Lengua de Fuego"] = "",
	["Tótem Lengua de Fuego II"] = "",
	["Tótem Lengua de Fuego III"] = "",
	["Tótem Lengua de Fuego IV"] = "",
	["Tótem Lengua de Fuego V"] = "",
	["Tótem Lengua de Fuego VI"] = "",
	["Tótem Lengua de Fuego VII"] = "",
	["Tótem Lengua de Fuego VIII"] = "",
	["Tótem de resistencia a la escarcha"] = "",
	["Tótem de resistencia a la escarcha II"] = "",
	["Tótem de resistencia a la escarcha III"] = "",
	["Tótem de resistencia a la escarcha IV"] = "",
	["Tótem de resistencia a la escarcha V"] = "",
	["Tótem de resistencia a la escarcha VI"] = "",
	["Tótem Corriente de sanación"] = "",
	["Tótem Corriente de sanación II"] = "",
	["Tótem Corriente de sanación III"] = "",
	["Tótem Corriente de sanación IV"] = "",
	["Tótem Corriente de sanación V"] = "",
	["Tótem Corriente de sanación VI"] = "",
	["Tótem Corriente de sanación VII"] = "",
	["Tótem Corriente de sanación VIII"] = "",
	["Tótem Corriente de sanación IX"] = "",
	["Tótem Fuente de maná"] = "",
	["Tótem Fuente de maná II"] = "",
	["Tótem Fuente de maná III"] = "",
	["Tótem Fuente de maná IV"] = "",
	["Tótem Fuente de maná V"] = "",
	["Tótem Fuente de maná VI"] = "",
	["Tótem Fuente de maná VII"] = "",
	["Tótem Fuente de maná VIII"] = "",
	["Tótem de magma"] = "",
	["Tótem de magma II"] = "",
	["Tótem de magma III"] = "",
	["Tótem de magma IV"] = "",
	["Tótem de magma V"] = "",
	["Tótem de magma VI"] = "",
	["Tótem de magma VII"] = "",
	["Tótem de resistencia a la Naturaleza"] = "",
	["Tótem de resistencia a la Naturaleza II"] = "",
	["Tótem de resistencia a la Naturaleza III"] = "",
	["Tótem de resistencia a la Naturaleza IV"] = "",
	["Tótem de resistencia a la Naturaleza V"] = "",
	["Tótem de resistencia a la Naturaleza VI"] = "",
	["Tótem abrasador"] = "",
	["Tótem abrasador II"] = "",
	["Tótem abrasador III"] = "",
	["Tótem abrasador IV"] = "",
	["Tótem abrasador V"] = "",
	["Tótem abrasador VI"] = "",
	["Tótem abrasador VII"] = "",
	["Tótem abrasador VIII"] = "",
	["Tótem abrasador IX"] = "",
	["Tótem abrasador X"] = "",
	["Tótem avizor"] = "",
	["Tótem Garra de piedra"] = "",
	["Tótem Garra de piedra II"] = "",
	["Tótem Garra de piedra III"] = "",
	["Tótem Garra de piedra IV"] = "",
	["Tótem Garra de piedra V"] = "",
	["Tótem Garra de piedra VI"] = "",
	["Tótem Garra de piedra VII"] = "",
	["Tótem Garra de piedra VIII"] = "",
	["Tótem Garra de piedra IX"] = "",
	["Tótem Garra de piedra X"] = "",
	["Tótem Piel de piedra"] = "",
	["Tótem Piel de piedra II"] = "",
	["Tótem Piel de piedra III"] = "",
	["Tótem Piel de piedra IV"] = "",
	["Tótem Piel de piedra V"] = "",
	["Tótem Piel de piedra VI"] = "",
	["Tótem Piel de piedra VII"] = "",
	["Tótem Piel de piedra VIII"] = "",
	["Tótem Piel de piedra IX"] = "",
	["Tótem Piel de piedra X"] = "",
	["Tótem Fuerza de la tierra"] = "",
	["Tótem Fuerza de la tierra II"] = "",
	["Tótem Fuerza de la tierra III"] = "",
	["Tótem Fuerza de la tierra IV"] = "",
	["Tótem Fuerza de la tierra V"] = "",
	["Tótem Fuerza de la tierra VI"] = "",
	["Tótem Fuerza de la tierra VII"] = "",
	["Tótem Fuerza de la tierra VIII"] = "",
	["Tótem de cólera"] = "",
	["Tótem de cólera II"] = "",
	["Tótem de cólera III"] = "",
	["Tótem de cólera IV"] = "",
	-- Hidden NPCs
	["Ejército de muertos"] = "",
	["Clarividente de la Luna Negra"] = "",
	["Drix Llavenegra"] = "",
	["Gnimo"] = "",
	["Hakmud de Argus"] = "",
	["Imagen del archimago Vargoth"] = "",
	["Diablillo en bola"] = "",
	["Mojodishu"] = "",
	["Necrófago resucitado"] = "",
	["Tótem de espíritus"] = "",
	["Antárbol"] = "",
	["Culebra venenosa"] = "",
	["Víbora"] = "",
}