--[[****************************************************************************
  *                           _VirtualPlates                                   *
  * Totems/Totems-frFR.lua - Localized TotemPlates table (fr-FR).              *
  ****************************************************************************]]

if ( GetLocale() ~= "frFR" ) then
	return;
end

local _VirtualPlates = select(2, ...)

local totemPath = "Interface\\AddOns\\!!!_VirtualPlates\\Textures\\Totems\\"
local npcPath = "Interface\\AddOns\\!!!_VirtualPlates\\Textures\\NPCs\\"

_VirtualPlates.TotemPlates = {
	-- Visible Totems
	["Totem de purification"] = totemPath .. "Cleansing Totem.blp",
	["Totem d'élémentaire de terre"] = totemPath .. "Earth Elemental Totem.blp",
	["Totem de lien terrestre"] = totemPath .. "Earthbind Totem.blp",
	["Totem d'élémentaire de feu"] = totemPath .. "Fire Elemental Totem.blp",
	["Totem de glèbe"] = totemPath .. "Grounding Totem.blp",
	["Totem de vague de mana"] = totemPath .. "Mana Tide Totem.blp",
	["Totem de séisme"] = totemPath .. "Tremor Totem.blp",
	["Totem Furie-des-vents"] = totemPath .. "Windfury Totem.blp",
	["Totem de courroux de l'air"] = totemPath .. "Wrath of Air Totem.blp",
	-- Visible NPCs
	["Etendard de bataille de l'Alliance"] = npcPath .. "Alliance Battle Standard.blp", 
	["Etendard de bataille de la Horde"] = npcPath .. "Horde Battle Standard.blp",
	["Ombrefiel"] = npcPath .. "Shadowfiend.blp",
	["Esprit du loup"] = npcPath .. "Spirit Wolf.blp",
	["Elémentaire d’eau"] = npcPath .. "Water Elemental.blp",
	-- Hidden Totems
	["Fire Resistance Totem"] = "",
	["Fire Resistance Totem II"] = "",
	["Fire Resistance Totem III"] = "",
	["Fire Resistance Totem IV"] = "",
	["Fire Resistance Totem V"] = "",
	["Fire Resistance Totem VI"] = "",
	["Flametongue Totem"] = "",
	["Flametongue Totem II"] = "",
	["Flametongue Totem III"] = "",
	["Flametongue Totem IV"] = "",
	["Flametongue Totem V"] = "",
	["Flametongue Totem VI"] = "",
	["Flametongue Totem VII"] = "",
	["Flametongue Totem VIII"] = "",
	["Frost Resistance Totem"] = "",
	["Frost Resistance Totem II"] = "",
	["Frost Resistance Totem III"] = "",
	["Frost Resistance Totem IV"] = "",
	["Frost Resistance Totem V"] = "",
	["Frost Resistance Totem VI"] = "",
	["Healing Stream Totem"] = "",
	["Healing Stream Totem II"] = "",
	["Healing Stream Totem III"] = "",
	["Healing Stream Totem IV"] = "",
	["Healing Stream Totem V"] = "",
	["Healing Stream Totem VI"] = "",
	["Healing Stream Totem VII"] = "",
	["Healing Stream Totem VIII"] = "",
	["Healing Stream Totem IX"] = "",
	["Mana Spring Totem"] = "",
	["Mana Spring Totem II"] = "",
	["Mana Spring Totem III"] = "",
	["Mana Spring Totem IV"] = "",
	["Mana Spring Totem V"] = "",
	["Mana Spring Totem VI"] = "",
	["Mana Spring Totem VII"] = "",
	["Mana Spring Totem VIII"] = "",
	["Magma Totem"] = "",
	["Magma Totem II"] = "",
	["Magma Totem III"] = "",
	["Magma Totem IV"] = "",
	["Magma Totem V"] = "",
	["Magma Totem VI"] = "",
	["Magma Totem VII"] = "",
	["Nature Resistance Totem"] = "",
	["Nature Resistance Totem II"] = "",
	["Nature Resistance Totem III"] = "",
	["Nature Resistance Totem IV"] = "",
	["Nature Resistance Totem V"] = "",
	["Nature Resistance Totem VI"] = "",
	["Searing Totem"] = "",
	["Searing Totem II"] = "",
	["Searing Totem III"] = "",
	["Searing Totem IV"] = "",
	["Searing Totem V"] = "",
	["Searing Totem VI"] = "",
	["Searing Totem VII"] = "",
	["Searing Totem VIII"] = "",
	["Searing Totem IX"] = "",
	["Searing Totem X"] = "",
	["Totem Sentinelle"] = "",
	["Stoneclaw Totem"] = "",
	["Stoneclaw Totem II"] = "",
	["Stoneclaw Totem III"] = "",
	["Stoneclaw Totem IV"] = "",
	["Stoneclaw Totem V"] = "",
	["Stoneclaw Totem VI"] = "",
	["Stoneclaw Totem VII"] = "",
	["Stoneclaw Totem VIII"] = "",
	["Stoneclaw Totem IX"] = "",
	["Stoneclaw Totem X"] = "",
	["Stoneskin Totem"] = "",
	["Stoneskin Totem II"] = "",
	["Stoneskin Totem III"] = "",
	["Stoneskin Totem IV"] = "",
	["Stoneskin Totem V"] = "",
	["Stoneskin Totem VI"] = "",
	["Stoneskin Totem VII"] = "",
	["Stoneskin Totem VIII"] = "",
	["Stoneskin Totem IX"] = "",
	["Stoneskin Totem X"] = "",
	["Strength of Earth Totem"] = "",
	["Strength of Earth Totem II"] = "",
	["Strength of Earth Totem III"] = "",
	["Strength of Earth Totem IV"] = "",
	["Strength of Earth Totem V"] = "",
	["Strength of Earth Totem VI"] = "",
	["Strength of Earth Totem VII"] = "",
	["Strength of Earth Totem VIII"] = "",
	["Totem of Wrath"] = "",
	["Totem of Wrath II"] = "",
	["Totem of Wrath III"] = "",
	["Totem of Wrath IV"] = "",
	-- Hidden NPCs
	["Armée des morts"] = "",
	["Diseuse de bonne aventure de la foire de Sombrelune"] = "",
	["Drix Finsterzang"] = "",
	["Image de l’archimage Vargoth"] = "",
	["Gnimo"] = "",
	["Hakmud d'Argus"] = "",
	["Diabloboule"] = "",
	["Mojodishu"] = "",
	["Goule ressuscitée"] = "",
	["Totem des esprits"] = "",
	["Tréant"] = "",
    ["Serpent venimeux"] = "",
	["Vipère"] = "",
}